name: Laravel CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@v2

      - name: Setup PHP environment ğŸ—
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install Composer dependencies ğŸ‘¨ğŸ»â€ğŸ’»
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Clear cache and optimize ğŸ§¹
        run: php artisan optimize:clear && php artisan optimize

      - name: Deploy to server ğŸš€
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: 103.210.69.72
          port: 22
          username: kelompok8
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /path/to/your/laravel/app
            git pull origin main
            php artisan migrate --force
          debug: true
