name: Laravel CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ðŸ›Ž
        uses: actions/checkout@v2

      - name: Setup PHP environment ðŸ—
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install Composer dependencies ðŸ‘¨ðŸ»â€ðŸ’»
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Clear cache and optimize ðŸ§¹
        run: php artisan optimize:clear && php artisan optimize

      - name: Deploy to server ðŸš€
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: 103.210.69.72
          username: User8
          key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDM5NHFz+ioWYWR3O3HWy4G732Vlc1pS54Bl0yDBF6ngZF/F4pmyJVXC7uubsiLzfb2iUC6wTBpHC0u8jxqFAnXO0pkmxlSKUQkZ0wY1qA5LhMQ/Gj71BBCaP/CHcpEOQCFPHl6T1trWy2tKW67UDyE>
          script: |
            cd /path/to/your/laravel/app
            git pull origin main
            php artisan migrate --force
